# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subBlock <- function(m, N, el, k) {
    .Call('_EMsigex_subBlock', PACKAGE = 'EMsigex', m, N, el, k)
}

matrixDiff <- function(m, N, TT, delta) {
    .Call('_EMsigex_matrixDiff', PACKAGE = 'EMsigex', m, N, TT, delta)
}

